/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel;

/**
 *
 * @author Дима
 */
public class AboutForm extends javax.swing.JFrame {

    /**
     * Creates new form AboutProgramm
     */
    public AboutForm() {
        initComponents();
        
         setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textInfoOne = new javax.swing.JLabel();
        textInfoTwo = new javax.swing.JLabel();
        textInfoThree = new javax.swing.JLabel();
        textInfoFour = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textInfoOne.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textInfoOne.setText("Мониторинг друзей из ВКонтакте");

        textInfoTwo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textInfoTwo.setText("Разработано: Ниткин Д.А");

        textInfoThree.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textInfoThree.setText("г.Омск, университет ОМГТУ");

        textInfoFour.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textInfoFour.setText("факультет ФИТиКС, кафедра АСОИУ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textInfoFour)
                    .addComponent(textInfoThree)
                    .addComponent(textInfoOne)
                    .addComponent(textInfoTwo))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(textInfoOne)
                .addGap(18, 18, 18)
                .addComponent(textInfoTwo)
                .addGap(18, 18, 18)
                .addComponent(textInfoThree)
                .addGap(18, 18, 18)
                .addComponent(textInfoFour)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AboutForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel textInfoFour;
    private javax.swing.JLabel textInfoOne;
    private javax.swing.JLabel textInfoThree;
    private javax.swing.JLabel textInfoTwo;
    // End of variables declaration//GEN-END:variables
}
