/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel;

import java.awt.event.WindowEvent;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import static panel.GatheringPanel.login;
import static panel.GatheringPanel.pass;
import static panel.GatheringPanel.numberPort;
import static panel.GatheringPanel.nameServer;

/**
 *
 * @author Дима
 */
public class EdgelistExportForm extends javax.swing.JFrame {

    /**
     * Creates new form SaveGraph
     */
    public EdgelistExportForm() {
        initComponents();
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        jList1.setModel(listModel);
        selectDatabase();

    }
    public static DefaultListModel listModel = new DefaultListModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        ok = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jList1);

        ok.setText("ОК");
        ok.setToolTipText("");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        cancel.setText("Отмена");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(ok)
                        .addGap(18, 18, 18)
                        .addComponent(cancel)))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ok)
                    .addComponent(cancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public static Connection c = null;
    public static Statement stmt = null;
    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed

        ExecutorService exec2 = Executors.newFixedThreadPool(1);
        exec2.submit(new Runnable() {
            @Override
            public void run() {

                ok.setEnabled(false);
                cancel.setEnabled(false);
                save();

            }

        });
        exec2.shutdown();

    }

    private void save() {
        Integer ind = jList1.getSelectedIndex();
        if (ind == -1) {
            JOptionPane.showMessageDialog(null, "Выберите пользователя", "", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        String name = (String) listModel.getElementAt(ind);
        ResultSet rsel_top = null;
        try {
            rsel_top = stmt.executeQuery("SELECT COUNT(*) as [Count] FROM " + name + ".dbo.BASE_TABLE"); //TODOTODO

        } catch (SQLException ex) {
            Logger.getLogger(AnalysisPanel.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
        String countvse = "";
        try {
            while (rsel_top.next()) {
                countvse = rsel_top.getString("Count");

            }
        } catch (SQLException ex) {
            Logger.getLogger(AnalysisPanel.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
        jProgressBar1.setStringPainted(true);
        jProgressBar1.setMinimum(0);
        jProgressBar1.setMaximum(countvse.equals("") ? 0 : Integer.valueOf(countvse));

        ResultSet rselbd = null;
        try {
            rselbd = stmt.executeQuery("SELECT * FROM " + name + ".dbo.BASE_TABLE");

        } catch (SQLException ex) {
            Logger.getLogger(GatheringPanel.class
                    .getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Не выполнился запрос к базе для выбора графа", "", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        try {
            String id;
            String parent;
            FileWriter writer2 = null;
            try {
                writer2 = new FileWriter(GatheringPanel.pathGraph + name + ".txt", false);

            } catch (IOException ex) {
                Logger.getLogger(EdgelistExportForm.class
                        .getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Ошибка с файлом для сохранения в него", "", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            int err = 0;
            while (rselbd.next()) {
                err++;
                jProgressBar1.setValue(err);
                id = rselbd.getString("id");
                parent = rselbd.getString("parent").replace("'", "");
                try {
                    writer2.write(id + " " + parent + "\n");

                } catch (IOException ex) {
                    Logger.getLogger(EdgelistExportForm.class
                            .getName()).log(Level.SEVERE, null, ex);
                }
            }
            try {
                writer2.close();
                //

            } catch (IOException ex) {
                Logger.getLogger(EdgelistExportForm.class
                        .getName()).log(Level.SEVERE, null, ex);

            }
        } catch (SQLException ex) {
            Logger.getLogger(GatheringPanel.class
                    .getName()).log(Level.SEVERE, null, ex);
        }

        try {
            c.close();

        } catch (SQLException ex) {
            Logger.getLogger(EdgelistExportForm.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "Готово", "", JOptionPane.INFORMATION_MESSAGE);
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }

    void selectDatabase() {

        SettingForm setting = new SettingForm();

        setting.setVisible(false);
        setting.dispatchEvent(new WindowEvent(setting, WindowEvent.WINDOW_CLOSING));

        SettingForm.installSettings();

        c = null;
        String user = login;
        String password = pass;
        String dbUrl = "jdbc:sqlserver://" + nameServer + ":" + numberPort + ";databaseName=master";
        stmt = null;

        try {
            c = DriverManager.getConnection(dbUrl, user, password);

        } catch (SQLException ex) {
            Logger.getLogger(EdgelistExportForm.class
                    .getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Не удалось установить соединение с базой", "", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        try {
            stmt = c.createStatement();

        } catch (SQLException ex) {
            Logger.getLogger(EdgelistExportForm.class
                    .getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Не удалось создать соединение с базой", "", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        ResultSet rselbd = null;
        try {
            rselbd = stmt.executeQuery("SELECT name, database_id, create_date FROM sys.databases ;");

        } catch (SQLException ex) {
            Logger.getLogger(GatheringPanel.class
                    .getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Не удалось выполнить запрос для вывода всех баз данных", "", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        listModel.removeAllElements();
        try {
            while (rselbd.next()) {

                String namedb = rselbd.getString("name");
                if (namedb != null && namedb.contains("_VK")) {
                    listModel.addElement(namedb);

                }
            }
            //
        } catch (SQLException ex) {
            Logger.getLogger(GatheringPanel.class
                    .getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_okActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EdgelistExportForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EdgelistExportForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EdgelistExportForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EdgelistExportForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EdgelistExportForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JList<String> jList1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton ok;
    // End of variables declaration//GEN-END:variables
}
