/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel;

import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Дима
 */
public class FiltersForm extends javax.swing.JFrame {

    /**
     * Creates new form FiltersForm
     */
    public FiltersForm() {
        initComponents();
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);

        if (!AnalysisPanel.countrySelect.equals("")) {
            country.setText(AnalysisPanel.countrySelect);
        }
        if (!AnalysisPanel.citySelect.equals("")) {
            city.setText(AnalysisPanel.citySelect);
        }

        jCheckBox1.setSelected(AnalysisPanel.isMan);
        jCheckBox2.setSelected(AnalysisPanel.isFemale);

        if (AnalysisPanel.ofAge != -5) {
            ageBefore.setText(String.valueOf(AnalysisPanel.ofAge));
        }
        if (AnalysisPanel.untilAge != -5) {
            ageAfter.setText(String.valueOf(AnalysisPanel.untilAge));
        }

        if (AnalysisPanel.circleToAnalysisPanel != -5) {
            circle.setText(String.valueOf(AnalysisPanel.circleToAnalysisPanel));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        countryL = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ageFrom = new javax.swing.JLabel();
        ok = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        country = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        ageBefore = new javax.swing.JTextField();
        before = new javax.swing.JLabel();
        ageAfter = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        circleL = new javax.swing.JLabel();
        circle = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        countryL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        countryL.setText("Страна");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Город");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Мужчина");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Женщина");

        ageFrom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ageFrom.setText("Возраст от");

        ok.setText("ОК");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        cancel.setText("Отмена");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        before.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        before.setText("до");

        circleL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        circleL.setText("Круг");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(countryL)
                                    .addComponent(jLabel2))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(country)
                                    .addComponent(city, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(ageFrom)
                                    .addComponent(jLabel3)
                                    .addComponent(circleL))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox1)
                                    .addComponent(jCheckBox2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(circle, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ageBefore, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addComponent(before)
                                        .addGap(18, 18, 18)
                                        .addComponent(ageAfter, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(cancel)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countryL)
                    .addComponent(country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jCheckBox1))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jCheckBox2))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageFrom)
                    .addComponent(ageBefore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(before)
                    .addComponent(ageAfter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(circleL)
                    .addComponent(circle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ok)
                    .addComponent(cancel))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed

        AnalysisPanel.countrySelect = country.getText();
        AnalysisPanel.citySelect = city.getText();
        AnalysisPanel.isMan = jCheckBox1.isSelected();
        AnalysisPanel.isFemale = jCheckBox2.isSelected();

        try {
            if (!ageBefore.getText().equals("")) {
                AnalysisPanel.ofAge = Integer.parseInt(ageBefore.getText());
                if (AnalysisPanel.ofAge < 0) {
                    JOptionPane.showMessageDialog(null, "Не корректный возраст", "InfoBox: ", JOptionPane.OK_CANCEL_OPTION);
                    return;
                }
            } else {
                AnalysisPanel.ofAge = -5;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Не корректный возраст", "InfoBox: ", JOptionPane.OK_CANCEL_OPTION);
            return;
        }
        try {
            if (!ageAfter.getText().equals("")) {
                AnalysisPanel.untilAge = Integer.parseInt(ageAfter.getText());
                if (AnalysisPanel.untilAge < 0) {
                    JOptionPane.showMessageDialog(null, "Не корректный возраст", "InfoBox: ", JOptionPane.OK_CANCEL_OPTION);
                    return;
                }
            } else {
                AnalysisPanel.untilAge = -5;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Не корректный возраст", "InfoBox: ", JOptionPane.OK_CANCEL_OPTION);
            return;
        }

        try {
            if (!circle.getText().equals("")) {
                AnalysisPanel.circleToAnalysisPanel = Integer.parseInt(circle.getText());
                if (AnalysisPanel.circleToAnalysisPanel < 0) {
                    JOptionPane.showMessageDialog(null, "Не корректное значение круга", "InfoBox: ", JOptionPane.OK_CANCEL_OPTION);
                    return;
                }
            } else {
                AnalysisPanel.circleToAnalysisPanel = -5;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Не корректное значение круга", "InfoBox: ", JOptionPane.OK_CANCEL_OPTION);
            return;
        }

        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));

    }//GEN-LAST:event_okActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FiltersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FiltersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FiltersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FiltersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FiltersForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageAfter;
    private javax.swing.JTextField ageBefore;
    private javax.swing.JLabel ageFrom;
    private javax.swing.JLabel before;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField circle;
    private javax.swing.JLabel circleL;
    private javax.swing.JTextField city;
    private javax.swing.JTextField country;
    private javax.swing.JLabel countryL;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton ok;
    // End of variables declaration//GEN-END:variables
}
