/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static panel.GatheringPanel.nameDB;
import static panel.GatheringPanel.login;
import static panel.GatheringPanel.pass;
import static panel.GatheringPanel.numberPort;
import static panel.GatheringPanel.nameServer;

/**
 *
 * @author Дима
 */
public class HistoryPanel extends javax.swing.JPanel {

    /**
     * Creates new form History_analisys
     */
    public HistoryPanel() throws SQLException {
        initComponents();
        jList1.setModel(listModel);
        setHistory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jTabbedPane1 = new javax.swing.JTabbedPane();

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setHistory() {
        if (MainForm.stat.size() > 0) {

            for (String ind : MainForm.stat.keySet()) {

                String name = ind;
                String val = MainForm.stat.get(ind);
                String massel[] = val.split(";");
                for (String vl : massel) {
                    String massconcr[] = vl.split("=");
                    if (massconcr[0].equals("id")) {
                        name += " - " + massconcr[1];
                    }
                    if (massconcr[0].equals("dop")) {
                        name += "\n ( " + massconcr[1]+" ) ";
                    }
                }
                listModel.addElement(name);
            }

        }
    }

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked

        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            evt.consume();
            Integer ind = jList1.getSelectedIndex();
            if (ind == -1) {
                JOptionPane.showMessageDialog(null, "Выберите пользователя", "", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            String select_name = (String) listModel.getElementAt(ind);
            String mass[] = select_name.split("-");
            String value = MainForm.stat.get(mass[0].replace(" ", ""));
            int i = 0;
            String city = "";
            String country = "";
            if (value != null) {
                jTabbedPane1.removeAll();
                String massel[] = value.split(";");
                for (String vl : massel) {
                    String massconcr[] = vl.split("=");
                    if (massconcr[0].equals("png")) {
                        JPanel pnlChart = new JPanel();
                        BufferedImage myPicture = null;
                        try {
                            myPicture = ImageIO.read(new File(massconcr[1].replace(" ", "") + ".png"));
                        } catch (IOException ex) {
                            Logger.getLogger(HistoryPanel.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        JLabel picLabel = new JLabel(new ImageIcon(myPicture));
                        pnlChart.add(picLabel);
                        jTabbedPane1.addTab(String.valueOf(i++), pnlChart);
                    }
                    if (massconcr[0].contains("cit")) {
                        city = massconcr[1].replace("cit=", "");
                    }
                    if (massconcr[0].contains("countr")) {
                        country = massconcr[1].replace("countr=", "");
                    }
                }

                InhabitationAnalysisForm sc = new InhabitationAnalysisForm(city, country);
                jTabbedPane1.addTab(String.valueOf(i++), sc);

            }

        }
    }//GEN-LAST:event_jList1MouseClicked
    public static boolean is_connect_hist = false;
    public Connection connect;
    public Statement stmt = null;
    private static DefaultListModel listModel = new DefaultListModel();



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
