/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static panel.GetData.NameDB;
import static panel.GetData.NameSarver;
import static panel.GetData.login;
import static panel.GetData.number_port;
import static panel.GetData.pass;

/**
 *
 * @author Дима
 */
public class History_analisis extends javax.swing.JPanel {

    /**
     * Creates new form History_analisys
     */
    public History_analisis() throws SQLException {
        initComponents();
        jList1.setModel(listModel);
        set();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jTabbedPane1 = new javax.swing.JTabbedPane();

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void set() {
        if (JFrame.stat.size() > 0) {

            for (String ind : JFrame.stat.keySet()) {

                String name = ind;
                String val = JFrame.stat.get(ind);
                String massel[] = val.split(";");
                for (String vl : massel) {
                    String massconcr[] = vl.split("=");
                    if (massconcr[0].equals("id")) {
                        name += " - " + massconcr[1];
                    }
                }
                listModel.addElement(name);
            }

        }
    }

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked

        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            evt.consume();
            Integer ind = jList1.getSelectedIndex();
            if (ind == -1) {
                JOptionPane.showMessageDialog(null, "Выберите пользователя", "", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            String select_name = (String) listModel.getElementAt(ind);
            String mass[] = select_name.split("-");
            String value = JFrame.stat.get(mass[0].replace(" ", ""));
            int i = 0;
            String city = "";
            String country = "";
            if (value != null) {
                jTabbedPane1.removeAll();
                String massel[] = value.split(";");
                for (String vl : massel) {
                    String massconcr[] = vl.split("=");
                    if (massconcr[0].equals("png")) {
                        JPanel pnlChart = new JPanel();
                        BufferedImage myPicture = null;
                        try {
                            myPicture = ImageIO.read(new File(massconcr[1].replace(" ", "") + ".png"));
                        } catch (IOException ex) {
                            Logger.getLogger(History_analisis.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        JLabel picLabel = new JLabel(new ImageIcon(myPicture));
                        pnlChart.add(picLabel);
                        jTabbedPane1.addTab(String.valueOf(i++), pnlChart);
                    }
                    if (massconcr[0].contains("cit")) {
                        city = massconcr[1].replace("cit=", "");
                    }
                    if (massconcr[0].contains("countr")) {
                        country = massconcr[1].replace("countr=", "");
                    }
                }

                city_count sc = new city_count(city, country);
                jTabbedPane1.addTab(String.valueOf(i++), sc);

            }

        }
    }//GEN-LAST:event_jList1MouseClicked
    public static boolean is_connect_hist = false;
    public Connection c;
    public Statement stmt = null;
    public static DefaultListModel listModel = new DefaultListModel();

    public void set_user_list() throws SQLException {

//        Setting_S setting = new Setting_S();
//        setting.set();
//        String user = login;
//        String password = pass;
//        String dbUrl = "jdbc:sqlserver://" + NameSarver + ":" + number_port + ";databaseName=master";
//        try {
//            if (!is_connect_hist) {
//                c = DriverManager.getConnection(dbUrl, user, password);
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Ошибка подключения к базе", "", JOptionPane.INFORMATION_MESSAGE);
//            return;
//        }
//        is_connect_hist = true;
//        stmt = c.createStatement();
//
//        ResultSet rsel;
//        rsel = stmt.executeQuery("SELECT name, database_id, create_date FROM sys.databases ;");
//        listModel.removeAllElements();
//        while (rsel.next()) {
//
//            String namedb = rsel.getString("name");
//            if (namedb != null && namedb.contains("VK")) {
//                listModel.addElement(namedb);
//            }
//        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
